'''
Script to generate the sunaku_hrm.dtsi file for the Adv360 keymap.
This generates the complex "Layer Sandwich" macros and cancellation layers
required for Sunaku's bilateral combinations.
'''

import os

header = """// Generated by generate_sunaku.py
// This file contains Sunaku's Bilateral Combinations "Layer Sandwich" implementation
// tailored specifically for the Adv360 keymap.

// Define the layers
#define LAYER_LeftPinky 7
#define LAYER_LeftRing 8
#define LAYER_LeftMiddle 9
#define LAYER_LeftIndex 10
#define LAYER_RightIndex 11
#define LAYER_RightMiddle 12
#define LAYER_RightRing 13
#define LAYER_RightPinky 14
"""

fingers = [
    {"name": "left_pinky", "layer_name": "LeftPinky", "key": "A", "mod": "LGUI", "type": "kp", "side": "left", "tapping_term": 350},
    {"name": "left_ring", "layer_name": "LeftRing", "key": "O", "mod": "9", "type": "mo", "side": "left", "tapping_term": 270},
    {"name": "left_middle", "layer_name": "LeftMiddle", "key": "E", "mod": "LSHFT", "type": "kp", "side": "left", "tapping_term": 270},
    {"name": "left_index", "layer_name": "LeftIndex", "key": "I", "mod": "8", "type": "mo", "side": "left", "tapping_term": 260},
    {"name": "right_index", "layer_name": "RightIndex", "key": "H", "mod": "8", "type": "mo", "side": "right", "tapping_term": 260},
    {"name": "right_middle", "layer_name": "RightMiddle", "key": "T", "mod": "RSHFT", "type": "kp", "side": "right", "tapping_term": 270},
    {"name": "right_ring", "layer_name": "RightRing", "key": "N", "mod": "9", "type": "mo", "side": "right", "tapping_term": 270},
    {"name": "right_pinky", "layer_name": "RightPinky", "key": "S", "mod": "RGUI", "type": "kp", "side": "right", "tapping_term": 350},
]

def generate_macros():
    out = ""
    for f in fingers:
        # Hold Macro
        out += f"        sunaku_{f['name']}_hold: sunaku_{f['name']}_hold {{\n"
        out += f"            compatible = \"zmk,behavior-macro-one-param\";\n"
        out += f"            wait-ms = <0>;\n            tap-ms = <0>;\n            #binding-cells = <1>;\n"
        out += f"            bindings = <&macro_press &{f['type']} {f['mod']}>\n"
        out += f"                     , <&macro_press &mo LAYER_{f['layer_name']}>\n"
        out += f"                     , <&macro_pause_for_release>\n"
        out += f"                     , <&macro_release &{f['type']} {f['mod']}>\n"
        out += f"                     , <&macro_release &mo LAYER_{f['layer_name']}>;\n"
        out += f"        }};\n\n"
        
        # Tap Macro (used for cancellation on same-hand press)
        out += f"        sunaku_{f['name']}_tap: sunaku_{f['name']}_tap {{\n"
        out += f"            compatible = \"zmk,behavior-macro-one-param\";\n"
        out += f"            wait-ms = <0>;\n            tap-ms = <0>;\n            #binding-cells = <1>;\n"
        
        mod_releases = []
        for mod_f in fingers:
            mod_releases.append(f"<&macro_release &{mod_f['type']} {mod_f['mod']}>")
        
        releases_str = "\n                     , ".join(mod_releases)
        
        out += f"            bindings = {releases_str}\n"
        out += f"                     , <&macro_tap &kp {f['key']}>;\n"
        out += f"        }};\n\n"
    return out


def generate_behaviors():
    out = ""
    for f in fingers:
        opposite_keys = "KEYS_R" if f['side'] == "left" else "KEYS_L"
        
        out += f"        sunaku_{f['name']}: sunaku_{f['name']} {{\n"
        out += f"            compatible = \"zmk,behavior-hold-tap\";\n"
        out += f"            label = \"SUNAKU_{f['name'].upper()}\";\n"
        out += f"            flavor = \"tap-preferred\";\n"
        out += f"            hold-trigger-key-positions = <{opposite_keys}>;\n"
        out += f"            hold-trigger-on-release;\n"
        out += f"            tapping-term-ms = <{f['tapping_term']}>;\n"
        out += f"            quick-tap-ms = <0>;\n"
        out += f"            require-prior-idle-ms = <180>;\n"
        out += f"            #binding-cells = <2>;\n"
        out += f"            retro-tap;\n"
        out += f"            bindings = <&sunaku_{f['name']}_hold>, <&kp>;\n"
        out += f"        }};\n\n"
    return out


def generate_layers():
    out = ""
    for f in fingers:
        out += f"        sunaku_layer_{f['name']} {{\n"
        out += f"            display-name = \"Unroll {f['key']}\";\n"
        
        bindings = ["&trans"] * 76
        
        left_alpha_indices = [
            1,2,3,4,5,
            15,16,17,18,19,
            29,30,31,32,33,
            47,48,49,50,51,
            67,68,69
        ]
        right_alpha_indices = [
            8,9,10,11,12,
            22,23,24,25,26,
            40,41,42,43,44,
            55,56,57,58,59,
            72,73,74
        ]
        
        cancel_indices = left_alpha_indices if f['side'] == "left" else right_alpha_indices
        
        keymap_mapping = {
            1: "N1", 2: "N2", 3: "N3", 4: "N4", 5: "N5",
            15: "Q", 16: "P", 17: "U", 18: "Y", 19: "SEMI",
            29: "A", 30: "O", 31: "E", 32: "I", 33: "G",
            47: "X", 48: "J", 49: "COMMA", 50: "EQUAL", 51: "SINGLE_QUOTE",
            67: "Z", 68: "C", 69: "V", 
            
            8: "N6", 9: "N7", 10: "N8", 11: "N9", 12: "N0",
            22: "K", 23: "F", 24: "L", 25: "R", 26: "B",
            40: "D", 41: "H", 42: "T", 43: "N", 44: "S",
            55: "C", 56: "M", 57: "W", 58: "V", 59: "DOT",
            72: "QUESTION", 73: "MINUS"
        }
        
        for idx in cancel_indices:
            if idx in keymap_mapping:
                bindings[idx] = f"&sunaku_{f['name']}_tap {keymap_mapping[idx]}"
        
        out += "            bindings = <\n"
        out += "                " + " ".join(bindings[0:7]) + "     " + " ".join(bindings[7:14]) + "\n"
        out += "                " + " ".join(bindings[14:21]) + "     " + " ".join(bindings[21:28]) + "\n"
        out += "                " + " ".join(bindings[28:35]) + " " + " ".join(bindings[35:39]) + " " + " ".join(bindings[39:46]) + "\n"
        out += "                " + " ".join(bindings[46:52]) + " " + " ".join(bindings[52:54]) + " " + " ".join(bindings[54:60]) + "\n"
        out += "                " + " ".join(bindings[60:65]) + " " + " ".join(bindings[65:71]) + " " + " ".join(bindings[71:76]) + "\n"
        out += "            >;\n        };\n\n"
    return out

import re

if __name__ == "__main__":
    defines_out = header
    macros_out = generate_macros()
    behaviors_out = generate_behaviors()
    layers_out = generate_layers()

    try:
        with open("config/adv360.keymap", "r") as f:
            keymap_content = f.read()

        # Regex replacements for each block
        keymap_content = re.sub(
            r"(// SUNAKU_DEFINES_START\n).*?(// SUNAKU_DEFINES_END)",
            rf"\1{defines_out}\2",
            keymap_content,
            flags=re.DOTALL
        )
        
        keymap_content = re.sub(
            r"(// SUNAKU_MACROS_START\n).*?(// SUNAKU_MACROS_END)",
            rf"\1{macros_out}        \2",
            keymap_content,
            flags=re.DOTALL
        )
        
        keymap_content = re.sub(
            r"(// SUNAKU_BEHAVIORS_START\n).*?(// SUNAKU_BEHAVIORS_END)",
            rf"\1{behaviors_out}        \2",
            keymap_content,
            flags=re.DOTALL
        )
        
        keymap_content = re.sub(
            r"(// SUNAKU_LAYERS_START\n).*?(// SUNAKU_LAYERS_END)",
            rf"\1{layers_out}        \2",
            keymap_content,
            flags=re.DOTALL
        )

        with open("config/adv360.keymap", "w") as f:
            f.write(keymap_content)

        print("Successfully injected Sunaku configurations into config/adv360.keymap!")
    except Exception as e:
        print(f"Error updating adv360.keymap: {e}")
